/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Duelers;

/**
 *
 * @author taghr
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
public class AddInvoice extends javax.swing.JFrame {

    /**
     * Creates new form AddInvoice
     */
    public AddInvoice() {
        initComponents();
        displayCustomers();
        displaySalesPerson();
        displayWarehouse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbaddInvoice = new javax.swing.JLabel();
        lbShippingAmount = new javax.swing.JLabel();
        lbInvoiceDate = new javax.swing.JLabel();
        lbCustomerList = new javax.swing.JLabel();
        combCustomerList = new javax.swing.JComboBox<>();
        lbInvoiceNo = new javax.swing.JLabel();
        lbTotalAmount1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtShippingAmount = new javax.swing.JTextField();
        txtInvoice = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnReturnInvoiceMenu = new javax.swing.JButton();
        lbSalespersonList = new javax.swing.JLabel();
        combSalespersonList = new javax.swing.JComboBox<>();
        lbProduct = new javax.swing.JLabel();
        combProductList = new javax.swing.JComboBox<>();
        lbWarehouse = new javax.swing.JLabel();
        combWarehouseList = new javax.swing.JComboBox<>();

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbaddInvoice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbaddInvoice.setText("Add Invoice");

        lbShippingAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbShippingAmount.setText("Shipping Amount");

        lbInvoiceDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInvoiceDate.setText("Date");

        lbCustomerList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCustomerList.setText("Select Customer");

        combCustomerList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combCustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combCustomerListActionPerformed(evt);
            }
        });

        lbInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInvoiceNo.setText("Invoice#");

        lbTotalAmount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTotalAmount1.setText("Total Amount");

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtShippingAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtShippingAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShippingAmountActionPerformed(evt);
            }
        });

        txtInvoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReturnInvoiceMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReturnInvoiceMenu.setText("Return");
        btnReturnInvoiceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnInvoiceMenuActionPerformed(evt);
            }
        });

        lbSalespersonList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSalespersonList.setText("Select Salesperson");

        combSalespersonList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lbProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbProduct.setText("Product");

        combProductList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//        combProductList.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                combProductListActionPerformed(evt);
//            }
//        });

        lbWarehouse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbWarehouse.setText("Warehouse");

        combWarehouseList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combWarehouseList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combWarehouseListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbShippingAmount)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnReturnInvoiceMenu)
                                        .addComponent(lbTotalAmount1))
                                    .addComponent(lbProduct))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                        .addComponent(txtShippingAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSubmit)
                                        .addGap(50, 50, 50)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCustomerList)
                                    .addComponent(lbInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSalespersonList))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate)
                            .addComponent(combCustomerList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combSalespersonList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combWarehouseList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(combProductList, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbaddInvoice)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbaddInvoice)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInvoiceNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInvoiceDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCustomerList)
                    .addComponent(combCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combSalespersonList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSalespersonList))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combWarehouseList))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combProductList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbShippingAmount)
                    .addComponent(txtShippingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalAmount1)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnInvoiceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combCustomerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combCustomerListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combCustomerListActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Connection conn;
        MyConnection addProduct = new MyConnection();
        conn = addProduct.getConnection();
        String selectedCust = combCustomerList.getSelectedItem().toString();
        String selectedSales = combSalespersonList.getSelectedItem().toString();
        String selectedInvoice = txtInvoice.getText();
        String selectedProduct = combProductList.getSelectedItem().toString();
        String selectedWarehouse = combWarehouseList.getSelectedItem().toString();
        String sql = "insert into Invoice (InvoiceID, invoiceDate, custID, salesID, UPC, warehouseID, " +
                "ShippingAmount, TotalAmount) "
        + "values ( '" + selectedInvoice + "' , '" + txtDate.getText() + "' , '" + selectedCust + "' , '" + selectedSales +
                "' , '" + selectedProduct + "' , '" + selectedWarehouse + "' , '" + txtShippingAmount.getText() +
                "' , '" + txtTotalAmount.getText() +"')";
        try {
            PreparedStatement pst= conn.prepareStatement(sql);
            pst.executeUpdate(sql);
            dispose();
            new Invoice().setVisible(true);

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }

//        boolean checked10 = checkBoxLess10.isSelected();
//        boolean checked30 = checkBoxGreater30.isSelected();
//        if(checked10) {
//             sql = "UPDATE invoice SET totalAmount = totalAmount - (totalAmount * .10) WHERE invoiceID = " + selectedInvoice;
//            try{
//                PreparedStatement pst= conn.prepareStatement(sql);
//                pst.executeUpdate(sql);
//                dispose();
//                new Invoice().setVisible(true);
//            }
//            catch(Exception ex){
//                JOptionPane.showMessageDialog(null, ex);
//            }
//        }
//        else if (checked30) {
//            sql = "UPDATE invoice SET totalAmount = totalAmount + (totalAmount * .02) WHERE invoiceID = " + selectedInvoice;
//            try{
//                PreparedStatement pst= conn.prepareStatement(sql);
//                pst.executeUpdate(sql);
//                dispose();
//                new Invoice().setVisible(true);
//            }
//            catch(Exception ex){
//                JOptionPane.showMessageDialog(null, ex);
//            }
//        }
//        else {
//            dispose();
//            new Invoice().setVisible(true);
//        }

    }
//GEN-LAST:event_btnSubmitActionPerformed
//not used
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        dispose();
        new Invoice().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnReturnInvoiceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInvoiceMenuActionPerformed
        dispose();
        new Invoice().setVisible(true);
    }//GEN-LAST:event_btnReturnInvoiceMenuActionPerformed

    private void combWarehouseListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combWarehouseListActionPerformed
        combProductList.removeAllItems();
        displayProduct();
    }//GEN-LAST:event_combWarehouseListActionPerformed
//
//    private void combProductListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combProductListActionPerformed
//    }//GEN-LAST:event_combProductListActionPerformed

    private void txtShippingAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShippingAmountActionPerformed
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection productCost = new MyConnection();
        conn = productCost.getConnection();
        String selectedProduct = combProductList.getSelectedItem().toString();
        String selectedCust = combCustomerList.getSelectedItem().toString();
        String sql = "Select SellingPrice from product WHERE UPC = " + selectedProduct;
        String taxSql = "Select salesTax from customer WHERE customerID = " + selectedCust;
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            PreparedStatement pst2 = conn.prepareStatement(taxSql);
            ResultSet rs2 = pst2.executeQuery();
            while(rs.next() && rs2.next()){
                double totalAmt = Double.parseDouble(txtShippingAmount.getText()) + rs.getDouble("SellingPrice");
                totalAmt += (totalAmt * (rs2.getDouble("salesTax")/100));
                txtTotalAmount.setText(String.valueOf(totalAmt));
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtShippingAmountActionPerformed


    private static void displayCustomers(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection customerList = new MyConnection();
        conn = customerList.getConnection();
        String sql = "Select customerID from customer ORDER BY customerID";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String customerID = Integer.toString(rs.getInt("customerID"));
                combCustomerList.addItem(customerID);
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    private static void displayProduct(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        String sql = "Select UPC from product WHERE warehouseNum =" + combWarehouseList.getSelectedItem().toString();
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                int UPC = Integer.parseInt(rs.getString("UPC"));
                combProductList.addItem(String.valueOf(UPC));
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void displayWarehouse() {
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        String sql = "Select warehouseNumber from warehouse ORDER BY warehouseNumber";

        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                int warehouseNumber = Integer.parseInt(rs.getString("warehouseNumber"));
                combWarehouseList.addItem(String.valueOf(warehouseNumber));
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private static void displaySalesPerson() {
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        String sql = "Select emp_ID from salesperson ORDER BY emp_ID";
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                int empID = Integer.parseInt(rs.getString("emp_ID"));
                combSalespersonList.addItem(String.valueOf(empID));
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturnInvoiceMenu;
    private javax.swing.JButton btnSubmit;
    private static javax.swing.JComboBox<String> combCustomerList;
    private static javax.swing.JComboBox<String> combProductList;
    private static javax.swing.JComboBox<String> combSalespersonList;
    private static javax.swing.JComboBox<String> combWarehouseList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCustomerList;
    private javax.swing.JLabel lbInvoiceDate;
    private javax.swing.JLabel lbInvoiceNo;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbSalespersonList;
    private javax.swing.JLabel lbShippingAmount;
    private javax.swing.JLabel lbTotalAmount1;
    private javax.swing.JLabel lbWarehouse;
    private javax.swing.JLabel lbaddInvoice;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtShippingAmount;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
