/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Duelers;

/**
 *
 * @author taghr
 */
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class AddInvoice extends javax.swing.JFrame {

    /**
     * Creates new form AddInvoice
     */
    static float calculateProductCost;
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public AddInvoice() {
        initComponents();
        displayCustomers();
        displaySalesPerson();
        displayWarehouse();
    }
    public void createInvoice(){
        MyConnection addProduct = new MyConnection();
        conn = addProduct.getConnection();
        try {
            //float total = Float.parseFloat(txtQuantity.getText())*calculateProductCost;
            String date = txtDate.getText();// + " 00:00";
            String selectedCust = combCustomerList.getSelectedItem().toString();
            String selectedSales = combSalespersonList.getSelectedItem().toString();
            String selectedInvoice = txtInvoice.getText();
            //String selectedProduct = combProductList.getSelectedItem().toString();
            String selectedWarehouse = combWarehouseList.getSelectedItem().toString();
            String sql =  "INSERT invoice (invoiceID, invoiceDate, custID, salesID,"
                    + " shippingAmount, totalAmount, paymentAmount, openStatus)" 
                    + " VALUES (" + selectedInvoice + ", '" + date + "', "
                    + selectedCust + ", " + selectedSales + ", "
                    + txtShippingAmount.getText() + ", "+ "0,0,1);";
            PreparedStatement pst= conn.prepareStatement(sql);
            //PreparedStatement pst2 = conn.prepareStatement(sqlProduct);
            //PreparedStatement pst3 = conn.prepareStatement(sqlAdd);
            pst.executeUpdate(sql);
            //pst2.executeUpdate(sqlProduct);
            //pst3.executeUpdate(sqlAdd);
            //displayInvoiceProduct();
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        lbaddInvoice = new javax.swing.JLabel();
        lbInvoiceDate = new javax.swing.JLabel();
        lbCustomerList = new javax.swing.JLabel();
        combCustomerList = new javax.swing.JComboBox<>();
        lbInvoiceNo = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtInvoice = new javax.swing.JTextField();
        lbSalespersonList = new javax.swing.JLabel();
        combSalespersonList = new javax.swing.JComboBox<>();
        lbProduct = new javax.swing.JLabel();
        combProductList = new javax.swing.JComboBox<>();
        lbWarehouse = new javax.swing.JLabel();
        combWarehouseList = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lbProduct1 = new javax.swing.JLabel();
        lbShippingAmount2 = new javax.swing.JLabel();
        lbProduct2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        invoiceProductTable = new javax.swing.JTable();
        btnAddProduct = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnReturnInvoiceMenu = new javax.swing.JButton();
        txtTotalAmount = new javax.swing.JTextField();
        lbShippingAmount1 = new javax.swing.JLabel();
        lbShippingAmount = new javax.swing.JLabel();
        txtShippingAmount = new javax.swing.JTextField();
        btnCalculateTotalAmount = new javax.swing.JButton();

        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbaddInvoice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbaddInvoice.setText("ADD INVOICE");

        lbInvoiceDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInvoiceDate.setText("Date");

        lbCustomerList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCustomerList.setText("Select Customer");

        combCustomerList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lbInvoiceNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInvoiceNo.setText("Invoice #");

        txtDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        /*
        java.sql.Date sqlDate = new java.sql.Date(System.currentTimeMillis())
        ;*/
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date sqlDate = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        txtDate.setText(dateFormat.format(sqlDate));
        //txtDate.setText(sqlDate);

        /*
        txtDate.setText("YYYY-MM-DD");
        */
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQuantity.setText("0");

        txtInvoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lbSalespersonList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSalespersonList.setText("Select Salesperson");

        combSalespersonList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lbProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbProduct.setText("Products List: ");

        combProductList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combProductList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combProductListActionPerformed(evt);
            }
        });

        lbWarehouse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbWarehouse.setText("Warehouse");

        combWarehouseList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combWarehouseList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combWarehouseListActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            //name, upc, price, quantity, warehouse,
            new String []{
                "UPC", "Name", "Cost", "Quantity", "Warehouse"}
        )

        {public boolean isCellEditable(int row, int column){
            return false;}}
    );
    jScrollPane3.setViewportView(productTable);

    lbProduct1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbProduct1.setText("Product");

    lbShippingAmount2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbShippingAmount2.setText("Enter Quantity");

    lbProduct2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbProduct2.setText("Invoice Products:");

    invoiceProductTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        //name, price, quantity, warehouse,total}
    new String [] {
        "UPC", "Name", "Cost", "Quantity", "Warehouse","Subtotal"}
    )

    {public boolean isCellEditable(int row, int column){
        return false;}}
);
jScrollPane4.setViewportView(invoiceProductTable);

btnAddProduct.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
btnAddProduct.setText("Add");
btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddProductActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbProduct1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combProductList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(12, 12, 12)
                            .addComponent(lbShippingAmount2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAddProduct))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(lbProduct))))
                    .addGap(45, 45, 45))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbInvoiceNo)
                            .addGap(18, 18, 18)
                            .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbInvoiceDate)
                                .addComponent(lbCustomerList)
                                .addComponent(lbSalespersonList)
                                .addComponent(lbWarehouse))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combCustomerList, 0, 164, Short.MAX_VALUE)
                                    .addComponent(combWarehouseList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combSalespersonList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(125, 125, 125))))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(lbaddInvoice))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(lbProduct2)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(lbaddInvoice)
            .addGap(18, 18, 18)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbInvoiceNo))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbInvoiceDate))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(combCustomerList)
                .addComponent(lbCustomerList))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(combSalespersonList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbSalespersonList))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(combWarehouseList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbWarehouse))
            .addGap(31, 31, 31)
            .addComponent(lbProduct)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(combProductList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbProduct1)
                .addComponent(lbShippingAmount2)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addComponent(lbProduct2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(37, Short.MAX_VALUE))
    );

    btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnSubmit.setText("Submit");
    btnSubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSubmitActionPerformed(evt);
        }
    });

    btnReturnInvoiceMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btnReturnInvoiceMenu.setText("Return");
    btnReturnInvoiceMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReturnInvoiceMenuActionPerformed(evt);
        }
    });

    txtTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txtTotalAmount.setEditable(false);

    lbShippingAmount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbShippingAmount1.setText("Total Amount");

    lbShippingAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbShippingAmount.setText("Shipping Amount");

    txtShippingAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txtShippingAmount.setText("0");

    btnCalculateTotalAmount.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
    btnCalculateTotalAmount.setText("Calculate");
    btnCalculateTotalAmount.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCalculateTotalAmountActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addGap(61, 61, 61)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbShippingAmount1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbShippingAmount)
                                .addGap(12, 12, 12)
                                .addComponent(txtShippingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculateTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReturnInvoiceMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btnSubmit))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculateTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbShippingAmount)
                        .addComponent(txtShippingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbShippingAmount1)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnReturnInvoiceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
//todolast
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        MyConnection addProduct = new MyConnection();
        conn = addProduct.getConnection();
        try {
            //float total = Float.parseFloat(txtQuantity.getText());
            String date = txtDate.getText() + " 00:00";
            String selectedCust = combCustomerList.getSelectedItem().toString();
            String selectedSales = combSalespersonList.getSelectedItem().toString();
            String sql = "UPDATE invoice SET invoiceDate = '" + date 
                    + "', custID = " + selectedCust +  ", salesID = " + selectedSales 
                    + ", shippingAmount = " + Float.parseFloat(txtShippingAmount.getText())
                    + ", totalAmount = " + Float.parseFloat(txtTotalAmount.getText())
                    + " WHERE invoiceID = " + txtInvoice.getText();
            /*
            float total = Float.parseFloat(txtQuantity.getText())*calculateProductCost;

            String selectedInvoice = txtInvoice.getText();
            //String selectedProduct = combProductList.getSelectedItem().toString();
            String selectedWarehouse = combWarehouseList.getSelectedItem().toString();
            
            String sql =  "INSERT invoice (invoiceID, invoiceDate, custID, salesID,"
                    + " warehouseID, shippingAmount, totalAmount, paymentAmount, openStatus)" 
                    + " VALUES (" + selectedInvoice + ",'" + date + "', "
                    + selectedCust + ", " + selectedSales + ", "
                    + selectedWarehouse + ", "+ txtShippingAmount.getText() + ", "
                    + total + ",'0','1');";
            /*
            String sqlAdd = "INSERT INTO invoice_product VALUES ("+selectedInvoice +", " 
                    + selectedProduct + ", " + txtQuantity.getText() + ");";
            String sqlProduct = "UPDATE product SET quantityAvailable = quantityAvailable - " 
                    + Integer.parseInt(txtQuantity.getText())
                    + ", quantitySold = quantitySold + " + Integer.parseInt(txtQuantity.getText())
                    + " WHERE upc = " + Integer.parseInt(selectedProduct)+";";
            */
            PreparedStatement pst= conn.prepareStatement(sql);
            //PreparedStatement pst2 = conn.prepareStatement(sqlProduct);
            //PreparedStatement pst3 = conn.prepareStatement(sqlAdd);
            pst.executeUpdate(sql);
            //pst2.executeUpdate(sqlProduct);
            //pst3.executeUpdate(sqlAdd);
            //displayInvoiceProduct();
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Invoice " + txtInvoice.getText() + 
                    ": Payment has been updated.");
        dispose();
        new Invoice().setVisible(true);
    }
//GEN-LAST:event_btnSubmitActionPerformed
//done
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        dispose();
        new Invoice().setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed
  //done
    private void btnReturnInvoiceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInvoiceMenuActionPerformed
        dispose();
        new Invoice().setVisible(true);
    }//GEN-LAST:event_btnReturnInvoiceMenuActionPerformed

    private void combWarehouseListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combWarehouseListActionPerformed
        //update product list
        combProductList.removeAllItems();
        displayProduct();
        
    }//GEN-LAST:event_combWarehouseListActionPerformed
//
    private void btnCalculateTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateTotalAmountActionPerformed
        calculateTotal();
    }//GEN-LAST:event_btnCalculateTotalAmountActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        //prevent user from editing custID and salesID after an invoice has been made
        if (txtInvoice.isEditable()){
            createInvoice();
            txtInvoice.setEditable(false);
        }
        //combCustomerList.setEnabled(false);
        //combSalespersonList.setEnabled(false);
        addProduct();
        //update product list
        combProductList.removeAllItems();
        displayProduct();
        //displayInvoiceProduct();
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void combProductListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combProductListActionPerformed
        // TODO add your handling code here:
        getProductCost();  
    }//GEN-LAST:event_combProductListActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        
        /*
        java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");       
        txtDate.setText(dateFormat.format(date));
                //            txtTotalAmount.setText(String.format("%.2f",total));
*/
    }//GEN-LAST:event_txtDateActionPerformed
    private void getProductCost(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection customerList = new MyConnection();
        conn = customerList.getConnection();
        String sql = "SELECT SellingPrice FROM product WHERE upc = "+combProductList.getSelectedItem()
                + " AND WarehouseNum = " + combWarehouseList.getSelectedItem();
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                calculateProductCost = rs.getFloat("SellingPrice");
            }           
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private static void calculateTotal(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection productCost = new MyConnection();
        conn = productCost.getConnection();
        float totalAmt;
        float subtotal = Float.parseFloat(txtTotalAmount.getText());
        
        
        //String selectedProduct = combProductList.getSelectedItem().toString();
        String selectedCust = combCustomerList.getSelectedItem().toString();
        //String sql = "Select SellingPrice from product WHERE UPC = " + selectedProduct;
        try{
            //pst = conn.prepareStatement(sql);
            //rs = pst.executeQuery();
            String taxSql = "SELECT salesTax from customer WHERE customerID = " + selectedCust;
            pst = conn.prepareStatement(taxSql);
            rs = pst.executeQuery();
            while(rs.next()){
                float tax = rs.getFloat("salesTax");
                
                totalAmt = subtotal + subtotal*(tax)+ Float.parseFloat(txtShippingAmount.getText());
                txtTotalAmount.setText(String.format("%.2f",totalAmt));

            }
            /*
            while(rs.next() && rs2.next()){
                double totalAmt = Double.parseDouble(txtQuantity.getText()) + rs.getDouble("SellingPrice");
                totalAmt += (totalAmt * (rs2.getDouble("salesTax")/100));
            }
            */
        //    pst.close();

        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void addProduct(){
        /*
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        */
        MyConnection addProduct = new MyConnection();
        conn = addProduct.getConnection();
        /*
        if(txtQuantity.getInt() >= 0)){
            
        }
        if(txtQuantity.getInt() == 0){
            calculateTotal();
        }
        */
        try {
            float totalProductAmount = Float.parseFloat(txtQuantity.getText())*calculateProductCost;
            String date = txtDate.getText() + " 00:00";
            String selectedCust = combCustomerList.getSelectedItem().toString();
            String selectedSales = combSalespersonList.getSelectedItem().toString();
            String selectedInvoice = txtInvoice.getText();
            String selectedProduct = combProductList.getSelectedItem().toString();
            String selectedWarehouse = combWarehouseList.getSelectedItem().toString();
            /*
            String sql =  "INSERT invoice (invoiceID, invoiceDate, custID, salesID,"
                    + " warehouseID, shippingAmount, totalAmount, paymentAmount, openStatus)" 
                    + " VALUES (" + selectedInvoice + ",'" + date + "', "
                    + selectedCust + ", " + selectedSales + ", "
                    + selectedWarehouse + ", "+ txtShippingAmount.getText() + ", "
                    + totalProductAmount + ",'0','1');";
            */
            String sqlAdd = "INSERT INTO invoice_product VALUES ("+selectedInvoice +", " 
                    + selectedProduct + ", " + txtQuantity.getText() + ", " + 
                    totalProductAmount + ");";
            String sqlProduct = "UPDATE product SET quantityAvailable = quantityAvailable - " 
                    + Integer.parseInt(txtQuantity.getText())
                    + ", quantitySold = quantitySold + " + Integer.parseInt(txtQuantity.getText())
                    + " WHERE upc = " + Integer.parseInt(selectedProduct)+" AND WarehouseNum = "
                    + selectedWarehouse + ";";
        
            //PreparedStatement pst= conn.prepareStatement(sql);
            PreparedStatement pst2 = conn.prepareStatement(sqlProduct);
            PreparedStatement pst3 = conn.prepareStatement(sqlAdd);
            //pst.executeUpdate(sql);
            pst2.executeUpdate(sqlProduct);
            pst3.executeUpdate(sqlAdd);
            displayInvoiceProduct();
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        //pst.close();                           
//        boolean checked10 = checkBoxLess10.isSelected();
//        boolean checked30 = checkBoxGreater30.isSelected();
//        if(checked10) {
//             sql = "UPDATE invoice SET totalAmount = totalAmount - (totalAmount * .10) WHERE invoiceID = " + selectedInvoice;
//            try{
//                PreparedStatement pst= conn.prepareStatement(sql);
//                pst.executeUpdate(sql);
//                dispose();
//                new Invoice().setVisible(true);
//            }
//            catch(Exception ex){
//                JOptionPane.showMessageDialog(null, ex);
//            }
//        }
//        else if (checked30) {
//            sql = "UPDATE invoice SET totalAmount = totalAmount + (totalAmount * .02) WHERE invoiceID = " + selectedInvoice;
//            try{
//                PreparedStatement pst= conn.prepareStatement(sql);
//                pst.executeUpdate(sql);
//                dispose();
//                new Invoice().setVisible(true);
//            }
//            catch(Exception ex){
//                JOptionPane.showMessageDialog(null, ex);
//            }
//        }
//        else {
//            dispose();
//            new Invoice().setVisible(true);
//        }
    }
    private static void deleteAllRows(DefaultTableModel model){
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }    
    }
    private void displayProduct(){
        /*
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        */
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        deleteAllRows(model);                  

        String sql = "SELECT ProductName, UPC, SellingPrice, quantityAvailable, warehouseNum"
                + " FROM product p WHERE warehouseNum = " + 
                combWarehouseList.getSelectedItem().toString() + " AND quantityAvailable > 0;";
 
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                String name = rs.getString("ProductName");
                String upc = rs.getString("UPC");
                float price = rs.getFloat("SellingPrice");
                int quantity = rs.getInt("quantityAvailable");
                int warehouse = rs.getInt("warehouseNum");
                Object[] products = {name, upc, price, quantity, warehouse};
                model = (DefaultTableModel) productTable.getModel();
                model.addRow(products);
                combProductList.addItem(upc);
            }
            pst.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void displayInvoiceProduct(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        //adds all productTotal
        float total = 0;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        DefaultTableModel model = (DefaultTableModel) invoiceProductTable.getModel();
        deleteAllRows(model);                  

        String sql = "SELECT ip.upc,p.ProductName, p.SellingPrice, ip.quantity, "
                + "p.warehouseNum, ip.productTotal FROM product p INNER JOIN "
                + "invoice_product ip ON p.upc = ip.upc WHERE ip.invoiceID = "
                + txtInvoice.getText();
 
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                int upc = rs.getInt("ip.upc");
                String name = rs.getString("p.ProductName");
                float price = rs.getFloat("p.SellingPrice");
                int quantity = rs.getInt("ip.quantity");
                int warehouse = rs.getInt("p.warehouseNum");
                float totalProduct = rs.getFloat("ip.productTotal");
                total+=totalProduct;
                Object[] products = {name, upc, price, quantity, warehouse,totalProduct};
                model = (DefaultTableModel) invoiceProductTable.getModel();
                model.addRow(products);
            }
            txtTotalAmount.setText(String.format("%.2f",total));
            pst.close();
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void displayCustomers(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection customerList = new MyConnection();
        conn = customerList.getConnection();
        String sql = "Select customerID from customer WHERE status = 'Active' OR status = 'active'";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String customerID = Integer.toString(rs.getInt("customerID"));
                combCustomerList.addItem(customerID);
            }
            pst.close();

        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    private static void displayWarehouse() {
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        String sql = "Select warehouseNumber FROM warehouse ORDER BY warehouseNumber";

        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                int warehouseNumber = Integer.parseInt(rs.getString("warehouseNumber"));
                combWarehouseList.addItem(String.valueOf(warehouseNumber));
            }
            pst.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }   
    private static void displaySalesPerson() {
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        String sql = "Select emp_ID from salesperson ORDER BY emp_ID";
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                int empID = Integer.parseInt(rs.getString("emp_ID"));
                combSalespersonList.addItem(String.valueOf(empID));
            }
        pst.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddInvoice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCalculateTotalAmount;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturnInvoiceMenu;
    private javax.swing.JButton btnSubmit;
    private static javax.swing.JComboBox<String> combCustomerList;
    private static javax.swing.JComboBox<String> combProductList;
    private static javax.swing.JComboBox<String> combSalespersonList;
    private static javax.swing.JComboBox<String> combWarehouseList;
    private static javax.swing.JTable invoiceProductTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCustomerList;
    private javax.swing.JLabel lbInvoiceDate;
    private javax.swing.JLabel lbInvoiceNo;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbProduct1;
    private javax.swing.JLabel lbProduct2;
    private javax.swing.JLabel lbSalespersonList;
    private javax.swing.JLabel lbShippingAmount;
    private javax.swing.JLabel lbShippingAmount1;
    private javax.swing.JLabel lbShippingAmount2;
    private javax.swing.JLabel lbWarehouse;
    private javax.swing.JLabel lbaddInvoice;
    private static javax.swing.JTable productTable;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtQuantity;
    private static javax.swing.JTextField txtShippingAmount;
    private static javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
