/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Duelers;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;   

/**
 *
 * @author taghr
 */
public class ViewModifyOpenInvoice extends javax.swing.JFrame {

    /**
     * Creates new form ViewModifyOpenInvoice
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    DefaultListModel invoiceModel;
    static float discount;
    public ViewModifyOpenInvoice() {
        initComponents();
        invoiceModel = new DefaultListModel();
        checkOpenInvoices();
        displayOpenInvoices();
        viewInvoice();
        modifyInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbModifyInvoice = new javax.swing.JLabel();
        lbInvoiceList = new javax.swing.JLabel();
        combInvoiceList = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnDoneViewSales = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        txtAddPayment = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        txtTotalAmount = new javax.swing.JTextField();
        txtRemaining = new javax.swing.JTextField();
        lbInvoiceList1 = new javax.swing.JLabel();
        lbInvoiceList2 = new javax.swing.JLabel();
        lbInvoiceList3 = new javax.swing.JLabel();
        lbInvoiceList4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbModifyInvoice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbModifyInvoice.setText("VIEW/MODIFY OPEN INVOICES");

        lbInvoiceList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbInvoiceList.setText("Invoice List:");

        combInvoiceList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combInvoiceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combInvoiceListActionPerformed(evt);
            }
        });

        btnDoneViewSales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoneViewSales.setText("Done");
        btnDoneViewSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneViewSalesActionPerformed(evt);
            }
        });

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            //id, date, custFirstName, custLastName, salesID,
            //productName, shipCost, totalAmount, custPayment
            new String [] {
                "Invoice ID", "Date", "Customer Name", "Salesperson ID",
                "Shipping Cost", "Total Amount",
                "Customer Payment"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}

    );
    jScrollPane2.setViewportView(invoiceTable);

    btnSubmit.setText("Submit");
    btnSubmit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSubmitActionPerformed(evt);
        }
    });

    lbInvoiceList1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbInvoiceList1.setText("Total Amount:");

    lbInvoiceList2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbInvoiceList2.setText("Payment Remaining:");

    lbInvoiceList3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbInvoiceList3.setText("ENTER AMOUNT:");

    lbInvoiceList4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    lbInvoiceList4.setText("All Open Invoices By Date:");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(38, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInvoiceList4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lbModifyInvoice)
                            .addGap(297, 297, 297))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbInvoiceList, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combInvoiceList, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbInvoiceList1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbInvoiceList2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(lbInvoiceList3)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDoneViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtAddPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSubmit)))
                    .addGap(299, 299, 299))))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(lbModifyInvoice)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbInvoiceList4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(21, 21, 21)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(56, 56, 56)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbInvoiceList)
                .addComponent(combInvoiceList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbInvoiceList1)
                .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbInvoiceList2)
                .addComponent(txtRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(48, 48, 48)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbInvoiceList3)
                .addComponent(txtAddPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSubmit))
            .addGap(52, 52, 52)
            .addComponent(btnDoneViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(73, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(317, 317, 317))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    private static void checkOpenInvoices(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;      
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        DefaultTableModel model = (DefaultTableModel) invoiceTable.getModel();
        deleteAllRows(model);
        float totalAmount;
        float shipCost;
        float custPayment;
        String sql = " SELECT invoiceID, shippingAmount, totalAmount, paymentAmount FROM invoice WHERE openStatus = 1 ";
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                String invoice = rs.getString("invoiceID");
                shipCost = rs.getFloat("shippingAmount");
                totalAmount = rs.getFloat("totalAmount");
                custPayment = rs.getFloat("paymentAmount");
                if (custPayment == totalAmount){
                    updateStatus(invoice);
                }
                        
            }
        }catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private static void updateStatus(String invoice){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst; 
        MyConnection update = new MyConnection();
        conn = update.getConnection();
        //String selectedInvoice = combInvoiceList.getSelectedItem().toString();
        String sql = "UPDATE invoice SET openStatus = 0 WHERE invoiceID = " + invoice;

        try{
            pst= conn.prepareStatement(sql);
            pst.executeUpdate(sql);
            //dispose();
            //new Invoice().setVisible(true);           
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void btnDoneViewSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneViewSalesActionPerformed
        dispose();
        new Invoice().setVisible(true);
    }//GEN-LAST:event_btnDoneViewSalesActionPerformed

    private void combInvoiceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combInvoiceListActionPerformed
        viewInvoice();
        modifyInvoice();
    }//GEN-LAST:event_combInvoiceListActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        MyConnection submitPayment = new MyConnection();
        conn = submitPayment.getConnection();
        String selectedInvoice = combInvoiceList.getSelectedItem().toString();
        String sql = "UPDATE invoice SET paymentAmount = paymentAmount + " + 
                txtAddPayment.getText() + " WHERE invoiceID = " + selectedInvoice;

        try{
            pst= conn.prepareStatement(sql);
            pst.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Invoice " + selectedInvoice + 
                    ": Payment has been updated.");
            //dispose();
            //new Invoice().setVisible(true);           
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        checkOpenInvoices();
        displayOpenInvoices();
        viewInvoice();
    }//GEN-LAST:event_btnSubmitActionPerformed
    private static void deleteAllRows(DefaultTableModel model){
        for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
            model.removeRow(i);
        }    
    }
    private static void displayOpenInvoices(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;      
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        DefaultTableModel model = (DefaultTableModel) invoiceTable.getModel();
        //refresh table
        deleteAllRows(model);
     
        String sql = "SELECT i.invoiceID, i.invoiceDate, c.firstName, c.lastName, "
                + "i.salesID, i.shippingAmount, i.totalAmount, "
                + "i.paymentAmount FROM invoice i INNER JOIN customer c "
                + "ON i.custID = c.customerID WHERE openStatus = 1 ORDER BY invoiceDate ASC;";
        try {
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                String id = rs.getString("i.invoiceID");
                Date date = rs.getDate("i.invoiceDate");
                String custFirstName = rs.getString("c.firstName");
                String custLastName = rs.getString("c.lastName");
                String salesID = rs.getString("i.salesID");
                //String product = rs.getString("i.upc");  
                float shipCost = rs.getFloat("shippingAmount");
                float totalAmount = rs.getFloat("totalAmount");
                float custPayment = rs.getFloat("paymentAmount");
                
                //DateFor
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                Object[] invoices = {id, date, custFirstName+" "+custLastName, salesID, 
                     shipCost, totalAmount, custPayment};
                
                model = (DefaultTableModel) invoiceTable.getModel();
                model.addRow(invoices);
            }
            
            
            
            
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private static void viewInvoice(){     
        //refresh list
        combInvoiceList.removeAllItems();
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        String sql = "SELECT invoiceID FROM invoice WHERE openStatus = 1 ORDER BY invoiceID;";

        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                String id = Integer.toString(rs.getInt("invoiceID"));
                combInvoiceList.addItem(id);
            }
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }    
    }
    private static void modifyInvoice(){
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;       
        MyConnection listAction = new MyConnection();
        conn = listAction.getConnection();
        try{
            String sql = "SELECT totalAmount, paymentAmount FROM invoice WHERE "
                    + "openStatus = 1 AND invoiceID = "
                    + combInvoiceList.getSelectedItem().toString() + ";"; 
            pst= conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {
                float total = rs.getFloat("totalAmount");
                
                txtTotalAmount.setText(String.format("%.2f",total));
                float paidAmount = rs.getFloat("paymentAmount");
                float paymentRemaining = total - paidAmount;
                txtRemaining.setText(String.format("%.2f",paymentRemaining));
            }
            
            //pst.close();
            
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewModifyOpenInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewModifyOpenInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewModifyOpenInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewModifyOpenInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewModifyOpenInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoneViewSales;
    private javax.swing.JButton btnSubmit;
    private static javax.swing.JComboBox<String> combInvoiceList;
    private static javax.swing.JTable invoiceTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbInvoiceList;
    private javax.swing.JLabel lbInvoiceList1;
    private javax.swing.JLabel lbInvoiceList2;
    private javax.swing.JLabel lbInvoiceList3;
    private javax.swing.JLabel lbInvoiceList4;
    private javax.swing.JLabel lbModifyInvoice;
    private javax.swing.JTextField txtAddPayment;
    private static javax.swing.JTextField txtRemaining;
    private static javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables
}
